### ISSUE TITLE
Reply already submitted & dialog not closing

### ISSUE THREAD

**Issue by kumar-aakash86** [kellvembarbosa/rate_app_dialog#1]
Great plugin but found few issues in this so far.

1. When I am trying to submit the feedback its showing this error & asking for choosing an email app.
`java.lang.IllegalStateException: Reply already submitted`

2. When I set **afterStarRedirect** it opens up the play store successfully but when I press back the dialog is still open with **Later**. It should dismiss.

3. Once the **minimeRequestToShow** completed & user choose later, its showing the dialog on each restart. If you can add some property to show this after the interval of 'n' launches it would be great.

One quick suggestion if you can add. It will we good for testing if we can reset all the current values as ones they are assigned there is no way to open the dialog again.
For now I am manually deleting all the rating related keys from sharedpreferences. But it will be nice to have an option for that.

 These are the things why I am holding the implementation of this in my app right now.

**Comment by kellvembarbosa** [comment]
I really liked your suggestion, about the error I will also correct, thanks for the feedback, I am open to new suggestions!

About requesting the email is an intentional action, through the standard email application of the cell phone, the user will send a feedback to your admin email defined when instantiating the plugin class.
Test on a real device and see how it looks in production...

======================
Finally I forgot the launch count, but tomorrow I'll add ...

**Comment by kumar-aakash86** [comment]
@kellvembarbosa 
Thanks for the updates. 

I was looking for some dialog which can send me the email if the user gave me low rating & submit the details in form. This way he will not be redirected to play store. Your package is the nearest one to that. 
May I suggest a callback when user try to submit the form after low rating. Inside that callback we can write any code according to our need. If we have the callback defined the email prop will omit its functionality & we get the callback triggered.

Let me know your input on this.
Also have you added the code for launch count. I am looking forward to that as well.

**Comment by kellvembarbosa** [comment]
I like your suggestion, I'm going to work on it today, and I'm also going to add the day counter before displaying the dialog ...

**Comment by kumar-aakash86** [comment]
Thanks in advance
